# Generated by Django 5.2.3 on 2025-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('medical', 'HAE-DNA-846, HAE-DNA-847'), ('engineering', 'HAE-DHNM-846, HAE-DHNM-847')], max_length=50)),
                ('message', models.TextField()),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='uploads/marksheets/')),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='uploads/aadhar/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
